### experiment config file
experiment_name: 'test'

paths:
  dataset: /cfs/earth/scratch/kraftjul/BA/data/dataset
  labels: /cfs/earth/scratch/kraftjul/BA/data/dataset/info/labels
  test_labels: /cfs/earth/scratch/kraftjul/BA/data/test_set_large
  md_output: /cfs/earth/scratch/kraftjul/BA/data/dataset/info/md_output

image_pipeline:
  to_rgb: true
  crop_by_bb: 1.0
  to_tensor: true
  resize: [224, 224]
  # can be a path to a .pt file to load stats, can be 'imagenet' to use the image net stats
  # or a dict with mean and std values fot each channel. if false it will not normalize
  normalize: /cfs/earth/scratch/kraftjul/BA/data/feature_stats.pt
  augmentation: null
  # augmentation:
  # - RandomHorizontalFlip: { p: 0.5 }
  # - ColorJitter:      { brightness: 0.2, contrast: 0.2 }

dataset:
  categories_to_drop: ['other', 'glis_glis']
  detector_model: null
  applied_detection_confidence: 0.25
  available_detection_confidence: 0.25
  random_seed: 55
  extra_test_set: null

data_module:
  batch_size: 32
  num_workers: 4
  pin_memory: true

cross_val:
  apply: true
  n_folds: 5
  test_fold: 0

model:
  backbone_name: efficientnet_b0
  backbone_pretrained: true
  backbone_weights: DEFAULT

  optimizer_name: AdamW
  optimizer_kwargs:
    lr: 0.001
    weight_decay: 0.00001
    amsgrad: false

  scheduler_name: CosineAnnealingLR
  scheduler_kwargs:
    T_max: 5
  
trainer:
  base_args:
    pred_writer_log_keys:
      - class_id
      - set
      - pred_id
      - probs
    pred_writer_prob_precision: 4
    accelerator: cpu
    patience: 5

  not_dev:
    log_every_n_steps: 10
    max_epochs: 1000

  trainer_kwargs: null

  do_predict: true

