name: project-env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pytorch-lightning=2.5.1
  - numpy=2.2.4
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - matplotlib-base=3.10.1
  - seaborn=0.13.2
  - pillow=9.4.0
  - tqdm=4.67.1
  - torchmetrics=1.7.1
  - jupyter
  - pip
  - pip:
    - megadetector