name: project-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - pytorch_lightning
  - torchmetrics
  - jupyter
  - pandas
  - numpy
  - seaborn
  - tqdm
  - pillow
  - scikit-learn
  - pip
  - pip:
    - megadetector
