### experiment config file
experiment_name: 'efficientnet_b0_v4_no_pretrained_cross_val'
dev_run: false

paths:
  dataset: /cfs/earth/scratch/kraftjul/BA/data/dataset
  labels: /cfs/earth/scratch/kraftjul/BA/data/dataset/info/labels
  test_labels: /cfs/earth/scratch/kraftjul/BA/data/test_set_large
  md_output: /cfs/earth/scratch/kraftjul/BA/data/dataset/info/md_output
  output_path: /cfs/earth/scratch/kraftjul/BA/output/runs

image_pipeline:
  to_rgb: true
  crop_by_bb: 1.0
  to_tensor: true
  resize: [224, 224]
  normalize: /cfs/earth/scratch/kraftjul/BA/data/feature_stats.pt
  augmentation: null

dataset:
  categories_to_drop: ['other', 'glis_glis']
  detector_model: null
  applied_detection_confidence: 0.5
  available_detection_confidence: 0.25
  random_seed: 55
  extra_test_set: null

data_module:
  batch_size: 64
  num_workers: 8
  pin_memory: true

cross_val:
  apply: true
  n_folds: 5
  test_fold: 0

model:
  backbone_name: efficientnet_b0
  backbone_pretrained: false
  backbone_weights: DEFAULT

  optimizer_name: AdamW
  optimizer_kwargs:
    lr: 0.0001
    weight_decay: 0.00001
    amsgrad: false

  scheduler_name: CosineAnnealingLR
  scheduler_kwargs:
    T_max: 50
  
trainer:
  base_args:
    pred_writer_log_keys:
      - class_id
      - set
      - pred_id
      - probs
    pred_writer_prob_precision: 4
    accelerator: gpu
    patience: 10

  not_dev:
    log_every_n_steps: 100
    max_epochs: 50

  trainer_kwargs:
    enable_progress_bar: true

  do_predict: true
