---
name: wild
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - jupyter
  - pandas
  - numpy
  - seaborn
  - tqdm
  - pillow
  - scikit-learn
  - pip
  - pip:
      - PytorchWildlife
