dataset: /cfs/earth/scratch/iunr/shared/iunr-mammaliabox/dataset/
labels: /cfs/earth/scratch/iunr/shared/iunr-mammaliabox/dataset/info/labels
md_output: /cfs/earth/scratch/iunr/shared/iunr-mammaliabox/dataset/info/md_output
output: /cfs/earth/scratch/kraftjul/BA/output